"""
This code is autogenerated - from AWS blueprints
Lambda function that sends an e-mail notofication about anomalies in candidates stream
"""
import base64
import boto3

snsClient = boto3.client('sns')
print('Loading function')

def lambda_handler(event, context):
    for record in event['Records']:
        # Kinesis data is base64 encoded so decode here
        payload = base64.b64decode(record['kinesis']['data'])
        response = snsClient.publish(
        TopicArn='arn:aws:sns:us-west-2:632826021673:candidates-topic',
        Message='Anomaly detected ...  ' + payload,
        Subject='Anomaly detected',
        MessageStructure='string',
        MessageAttributes={
        'String': {
            'DataType': 'String',
            'StringValue': 'New records have been processed.'
            }
        }
    )
    return 'Successfully processed {} records.'.format(len(event['Records']))
